Change misleading comment.
Not calling `ModuleDoc.__init__(self)` causes `duid` to be unset and exceptions like this:

Traceback (most recent call last):
  File "mydesign.py", line 299, in <module>
    main()
  File "mydesign.py", line 292, in main
    generate_docs(soc, "build/"+target+"/documentation")
  File ".../litex/litex/litex/soc/doc/__init__.py", line 98, in generate_docs
    documented_region = DocumentedCSRRegion(
  File ".../litex/litex/litex/soc/doc/csr.py", line 80, in __init__
    docs = module.get_module_documentation()
  File ".../litex/litex/litex/soc/integration/doc.py", line 141, in gatherer
    return sorted(r, key=lambda x: x.duid)
  File ".../litex/litex/litex/soc/integration/doc.py", line 141, in <lambda>
    return sorted(r, key=lambda x: x.duid)
  File ".../litex/migen/migen/fhdl/module.py", line 136, in __getattr__
    raise AttributeError("'"+self.__class__.__name__+"' object has no attribute '"+name+"'")
AttributeError: 'CDCUsbPHY' object has no attribute 'duid'